[channel]
generator = utipod
xmlbase = http://174.93.162.91:8080/UCzNolHig0VbauCEGbj0PHrg
title = "hupstream"
link = https://www.youtube.com/channel/UCzNolHig0VbauCEGbj0PHrg
description = "hupstream is a France-based Open Source engineering Studio.\n\nWe help people and companies make the most of Open Source and Linux: tools, technologies, communities, collaboration and development practices.\n\nWe offer custom Linux systems and software package design, setup and maintenance for your projects. We can help your team with the right, solid tools to build and maintain their own Linux distribution.\n\nWe organize training sessions and developers meeting events (Kernel Recipes & Distro Recipes)."

[channel "image"]
url = https://yt3.ggpht.com/ytc/AKedOLTfjg0A5YAtrcGyH0VE6B3ANPZh_I4wwZgEtsww=s0

