[item]
guid = -5T4Cjw46ys
title = "Kernel Recipes 2019 - Faster IO through io_uring"
description = "Since the dawn of time, Linux has had to make do with inferior IO interfaces. Native Linux AIO supports only a niche application class (O_DIRECT), and even for that use case, it’s far too slow for modern storage. This talk will detail io_uring, a modern IO interface for Linux, that’s both fully featured and performant.\nJens Axboe"
author = hupstream
source = https://www.youtube.com/channel/UCzNolHig0VbauCEGbj0PHrg
link = https://www.youtube.com/watch?v=-5T4Cjw46ys
category = "Science & Technology"
pubdate = Fri, 11 Oct 2019 00:00:00 -0000
enclosure = -5T4Cjw46ys.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/-5T4Cjw46ys/sddefault.webp

