[item]
guid = JgJQpcaaCR8
title = "Kernel Recipes 2019 - XDP closer integration with network stack"
description = "XDP (eXpress Data Path) is the new programmable in-kernel fast-path, which is placed as a layer before the existing Linux kernel network stack (netstack).\n\nWe claim XDP is not kernel-bypass, as it is a layer before and it can easily fall-through to netstack. Reality is that it can easily be (ab)used to create a kernel-bypass situation, where non of the kernel facilities are used (in form of BPF-helpers and in-kernel tables). The main disadvantage with kernel-bypass, is the need to re-implement everything, even basic building blocks, like routing tables and ARP protocol handling.\n\nIt is part of the concept and speed gain, that XDP allows users to avoid calling part of the kernel code. Users have the freedom to do kernel-bypass and re-implement everything, but the kernel should provide access to more in-kernel tables, via BPF-helpers, such that users can leverage other parts of the Open Source ecosystem, like router daemons etc.\n\nThis talk is about how XDP can work in-concert with netstack, and proposal on how we can take this even-further. Crazy ideas like using XDP frames to move SKB allocation out of driver code, will also be proposed.\n\nJesper Dangaard Brouer"
author = hupstream
source = https://www.youtube.com/channel/UCzNolHig0VbauCEGbj0PHrg
link = https://www.youtube.com/watch?v=JgJQpcaaCR8
category = "Science & Technology"
pubdate = Tue, 08 Oct 2019 00:00:00 -0000
enclosure = JgJQpcaaCR8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/JgJQpcaaCR8/maxresdefault.webp

