[item]
guid = sZMNm1o7FQw
title = "Embedded Recipes 2019 - RT is about to make it to mainline. Now what?"
description = "The PREEMPT_RT (aka real-time patch) started back in 2004. Since then, a lot of it has made it into the kernel. The only part left is the change of turning spinning locks into mutexes, then the merge of the PREEMPT_RT patch will be complete. This is expected to happen no later than the Q1 of 2020. But once it is in, how can you take advantage of it? This talk will discuss the basics of writing a real-time application, and some tricks to play with Linux configured with PREEMPT_RT."
author = hupstream
source = https://www.youtube.com/channel/UCzNolHig0VbauCEGbj0PHrg
link = https://www.youtube.com/watch?v=sZMNm1o7FQw
category = "Science & Technology"
pubdate = Fri, 04 Oct 2019 00:00:00 -0000
enclosure = sZMNm1o7FQw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/sZMNm1o7FQw/sddefault.jpg

